# Generated by Django 4.0.3 on 2022-05-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartment_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_appartment',
            name='status',
            field=models.CharField(default='notapproved', max_length=100, null=True),
        ),
    ]
