# Generated by Django 4.0.3 on 2022-05-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appartment_App', '0003_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facility',
        ),
    ]
