# Generated by Django 4.0.3 on 2022-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartment_App', '0004_delete_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_now',
            name='facility',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
