# Generated by Django 4.0.3 on 2022-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartment_App', '0005_book_now_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_now',
            name='status2',
            field=models.CharField(default='notapproved', max_length=100, null=True),
        ),
    ]
