# Generated by Django 4.0.3 on 2022-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartment_App', '0006_alter_book_now_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_now',
            name='facility_amount',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
